### ISSUE TITLE
Support render prop pattern to avoid rendering a wrapper

### ISSUE THREAD

**Issue by Pajn** [greena13/react-hotkeys#103]
First of all, I do not want to remove the current behavior, only add to it. So this would continue to work with all existing code using `react-hotkeys`.

I need to have a high control of the rendered DOM and react-hotkeys wrapper does cause a mess for me currently. To avoid rendering a wrapper and give the user better control of the DOM `react-hotkeys` could optionally support the render prop pattern for its children. That is, if children is a function instead of a ReactElement `react-hotkeys` would call it instead of rendering extra DOM.

So this:
```
<HotKeys>
  {props => <div {...props} />}
</HotKeys>
```
would be equivalent to this:
```
<HotKeys>
  <div />
</HotKeys>
```

but with one less DOM element.

If you are interested in this I can provide a PR

**Comment by greena13** [comment]
This is an interesting idea. Do you need control over what's rendered inside the `HotKeys` component, or do you need control over what the `HotKeys` renders its children in (currently a `div` by default)?

**Comment by Pajn** [comment]
The thing is that I have multiple "provider style" components for hotkeys, drag and drop, context menu etc. 

If all of these provides there own DOM-element the DOM looks like this:
```
<div>
  <div>
    <div>
     <div />
   </div>
  </div>
</div>
```

And unnecessarily nested DOM elements creates multiple problems. Most severely it effects CSS grid layout as the nesting completely puts me out of the parent grid and complicates the layout quite a lot. The extra nesting is only a problem for decedent `HotKeys` elements and not the top level one as there isn't any layout going on there.

If all of these lets me render the DOM element myself, I can make sure there is only one (of course I would have to resolve collisions for things like event handlers and not just blindly apply everything).

**Comment by greena13** [comment]
I believe I understand the issue that you are experiencing - it is one that I and many others have encountered. However, I have a few hesitations with adopting your suggested solution:

* I have not encountered this particular convention of accepting functions as React component `children` before. I'll reserve judgement on it for now, but are you able to link me to, or otherwise convince me that this is a widely practiced convention in well-known and well-supported React libraries?
* This problem is partially mitigated by being able to chose what component wraps the children via the `component` prop. I understand that this does not go very far to addressing how grid layouts break when wrapped by unnecessary parent components.
* This issue, I believe, will be addressed in version 2.0.0 of this package, which does not need to apply a parent wrapper. Unfortunately, that is still probably a couple of months away from a stable release as my efforts are currently needed elsewhere. But as I am already trying to re-implement all of the existing functionality of v1 so that the upgrade path will be as seamless as possible, I am reluctant to add more functionality that I will inevitably have to match before I can release v2.0.0.

I realise my resistance may be frustrating to hear, but I have concerns about solving this problem in a fashion that will delay or need to be dropped in v2.0.0. If you can convince me this is a common solution to this problem in the larger React ecosystem, I may be talked into supporting it - even if only as a stop-gap until v2.0.0. But I would have to find the time to think through the implications of doing so.

**Comment by Pajn** [comment]
> are you able to link me to, or otherwise convince me that this is a widely practiced convention in well-known and well-supported React libraries?

You'll be the decider of that, but I think so! :)
It's popularity is quite new but have grown very big. Some well known examples:
- *React* itself. React 16.3 opted to use this pattern over HOCs for the new Context API https://reactjs.org/blog/2018/03/29/react-v-16-3.html#official-context-api
- *Downshift* (maintained by Paypal) https://github.com/paypal/downshift#children-function
- *Apollo* opted to add it in addition to their existing HOC API https://www.apollographql.com/docs/react/react-apollo-migration.html#query-component
- *React router* https://reacttraining.com/react-router/web/api/Route/children-func

There are more examples as well but these were some well maintained, popular ones I could remember on top of my head. A quick Google search showed me this https://github.com/jaredpalmer/awesome-react-render-props which lists quite a few of them but I have not gone through and actually verified that list though.

**Comment by greena13** [comment]
I think the need for this should be addressed by the new [withHotKeys HoC API](https://github.com/greena13/react-hotkeys/tree/2.0.0-pre1#withhotkeys-hoc-api) in [v2.0.0-pre1](https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre1) when it's released, soon.
