### ISSUE TITLE
Get parent focus after on focus out of a children component

### ISSUE THREAD

**Issue by arnonnir** [greena13/react-hotkeys#112]
Hey!
I am using the HotKeys for a parent component and for child component.
I have a case that the child component focus out and the focus return to the body and not to the parent component.

There is a solution for that?
I can solve it for this case in specific but I am looking for a general solution without doing it manually for each case like that.

Thanks!

**Comment by greena13** [comment]
Hey arnonnir, 

How is the child losing focus? Is it from the user pressing tab (or some other key on the keyboard), or is it from them clicking elsewhere in the document?

**Comment by arnonnir** [comment]
From the user pressing key on the keyboard. for example, the user pressed enter in order to select value and then the the child component unmounted, then, the focus returned to the body and not to parent component.

**Comment by arnonnir** [comment]
@greena13  Do you have any solution for that>

**Comment by tageecc** [comment]
@greena13 any updates? i have problem similarly

**Comment by greena13** [comment]
The short answer is "no, not really". 

React hotkeys doesn't provide any way to handle this in a particularly declarative or reusable fashion. 

As I'm sure you have already surmised, you can do something in the `componentWillUnmount()` method of the child to re-focus the parent when the child unmounts. You may also be able to add siblings with [`tabIndex`](https://github.com/greena13/react-hotkeys#tab-order) that keep the focus in the parent when the child unmounts.

I'm closing for now as I suspect you have long since moved on. But a feature that covers this may be added in the future.
