### ISSUE TITLE
Keypress triggered multiple unfocused handlers

### ISSUE THREAD

**Issue by steobrien** [greena13/react-hotkeys#118]
Thanks for maintaining this great library.

We’ve encountered a case in our app where a single keypress event gets sent to several unfocused `<HotKeys>` instances.

This happens for a specific master-detail style set of views, as the following example illustrates.

# Example:

See this example functioning: https://codesandbox.io/s/m55x8x1jnj (using latest version of this library, 1.1.4).

- We have a list of `<Item>`s in a parent component
- The parent component defines an `activeItemIndex`
- Only one `<Item>` has `isActive` at a time (when its index in the list equals `activeItemIndex`)
- Each `<Item>` internally has a `<HotKeys>`, attached to window, but only `focused` if `isActive`.
- On <kbd>d</kbd> press, an `isActive` `<Item>` asks the parent component to remove it 

### Expected behavior:
- The `hasActive` `<Item>` is removed from the list when <kbd>d</kbd> is pressed

### Actual behavior:
- The `hasActive` `<Item>` is removed from the list when <kbd>d</kbd> is pressed, **as well as all items following it** 😱 

<hr>

Just want to double check this isn’t somehow intended behavior. Happy to take a look at fixing this if you agree it’s a bug!

**Comment by steobrien** [comment]
Hey @greena13, any chance you could confirm that this is a bug?

**Comment by greena13** [comment]
Hey, @steobrien. Thanks for the clear write-up.

`focused` is unfortunately one of the features of this library that I think could have been implemented better. It was added, I believe, as a way to attach global handlers, but was given an unfortunate name. It's one of the things I want to remove in the next major version of the package (I'm still struggling to find the time to finish the damn thing off).

Basically the code you have used will add a global listener for every `<Item>` you mount to the DOM. So, when you press `d` once, the handler is called the first time and correctly unmounts the intended `<Item>`. Now the `<Item>` after the active one, is in the active one's place in the list. The handler is called a second time (assuming you have more than 1 `<Item>` in your list) - and this next `Item` is (incorrectly) removed. This repeats until all of the `<Item>`s that follow the active one have been removed (and then continues for however many items were before it in the list, but this effectively is a no operation as there are no more `<Item>`s left to occupy the active place).

If you must use `focused` (i.e. you need a global hotkey without selecting anything in the DOM and you can't programmatically set the focus on mount for some reason) I'd recommend placing a single `<HotKeys>` on the parent instead of one on each `<Item>`. This will bind a single global listener and should function as intended.

An alternative - which is superior if your use-case allows it - is to *not* use `focused`, and instead [programmatically focus the parent on mount](https://github.com/greena13/react-hotkeys#programmatically-manage-focus). You should still move to a single `<HotKeys>` on the parent, regardless of which approach you choose.

**Comment by steobrien** [comment]
Thanks @greena13, much appreciated. We’ll migrate away from using `focused` on sibling-children, and reconsider using it entirely.
