### ISSUE TITLE
Nested HotKeys break modifier key handling in 2.0.0-pre1

### ISSUE THREAD

**Issue by OliverColeman** [greena13/react-hotkeys#132]
I have nested HotKeys components which use a keymap with key combination 'ctrl+z', with different handlers for the different HotKeys components. When the focus is in the most-nested component I'm finding that the initial (and sometimes second) press of the `ctrl` key is ignored, with the log output showing `HotKeys (FT3📙-E23🧡-C2🔷):' Ignored 'Control' keydown event because it had an old focus tree id: ` for every key press that doesn't work. The component containing the most-nested HotKeys (`MaskEditorCanvas` below) is not being re-rendered when pressing `ctrl`.

I've fiddled around with how focus is handled in the most-nested HotKeys component, and tried to make sure that nothing is re-rendered that doesn't need to be, to no avail. I couldn't find any options for ignoring whether the focus tree matters (for modifier keys at least).

I was using version 1.1.4 and did not have this issue with the same code. I upgraded to 2.0.0-pre1 to address an issue around event propagation to parent HotKeys components.

The code for component with the most-nested HotKeys is 
```
import React from 'react';
import {HotKeys} from 'react-hotkeys';

const autoFocusElStyle={position:'absolute', width:0, height:0, borderStyle:'none', padding:0, margin:0};

class MaskEditorCanvas extends React.Component {
  constructor(props) {
    super(props);
    ...
    this.keyboardShortcuthandlers = {
      'close': this.handleCancelTool,
      'del': this.handleUndo,
      'undo': this.handleUndo,
    };
    ...
    this.maskEditorCanvasStyle = {
      opacity: props.canvasOpacity,
      width: props.width * props.zoom,
      height: props.height * props.zoom,
    };
  }

  componentDidUpdate() {
    this.autoFocusElRef.focus();
  }

  ...

  render() {
    const { width, height, canvasOpacity, zoom, showHoverLabel } = this.props;
    const { hoverLabel, hoverX, hoverY } = this.state;

    console.log("rc");

    return (
      <HotKeys handlers={this.keyboardShortcuthandlers} className="canvas-hotkeys-wrapper">
        {/*hack to set react tree focus inside the HotKeys component, so we can zoom before clicking anywhere. */}
        <button style={autoFocusElStyle} ref={this.autoFocusElRefFn}  />

        <div className="MaskEditorCanvas"
          style={this.maskEditorCanvasStyle}
        >
          <canvas ref={this.canvasRefFn} width={width} height={height} />
          <canvas ref={this.canvasRefTempFn}  width={width} height={height}
              onMouseDown={this.onMouseDown}
              onMouseMove={this.onMouseMove}
              onMouseUp={this.onMouseUp}
              onDoubleClick={this.onDoubleClick}
              onMouseLeave={this.onMouseLeave}
          />
        </div>

        { showHoverLabel && hoverLabel &&
          <div
            className="hover-class-label"
            style={{
              top: hoverY*zoom + (hoverY > 50 ? -40 : 10),
              left: hoverX*zoom + 10,
            }}
          >
            {hoverLabel}
          </div>
        }
      </HotKeys>
    )
  }
}

export default MaskEditorCanvas;
```

**Platform (please complete the following information):**
- Version of react-hotkeys: 2.0.0-pre1
- Browser:
  - Chrome  66.0.3359.139 (Official Build) (64-bit)
  - Firefox 64
- OS: Linux

**What Configuration options are you using?**
```
configure({
  logLevel: 'verbose'
});
```

**Comment by greena13** [comment]
Hey Oliver,

Thanks for the great write-up of your issue and taking the time to try the new pre-release.

## Some background on how the library is supposed to work (not necessarily how it is, in this context)

The `Ignored 'Control' keydown event because it had an old focus tree id` message normally occurs when a `HotKeys` component is currently in focus and its own handler (or that of one of its focus descendant `HotKeys` components) causes it to lose focus (call `onBlur`) or unmount (call `componentWillUnmount`). 

So if you imagine you have 3 levels of `HotKeys`, with the most deeply nested on the right:

```
<HotKeys Grandparent> - <HotKeys Parent> - <HotKeys Grandchild>
```

If the innermost component is in focus, and a key is pressed, React propagates the event up to the first `<HotKeys>` component that has `actions` defined, which then sorts out which handler should be called (the handlers defined in the component closest to the event's `target`, first). 

If an action was defined on `<HotKeys Parent>` and a handler was defined on `<HotKeys Grandchild>` which causes a change in focus, or for a `<HotKeys>` component to unmount, the focus tree is incremented. After calling the handler (which changes focus), React resumes on propagating the key event up to `<HotKeys Grandparent>`, which tries to register the event with `react-hotkeys` who ignores it because `<HotKeys Grandparent>` reports it is part of the old focus tree.

## Your situation

You said the inner component is not being re-rendered. I take this to mean the `componentDidUpdate()` method is not being called, which sets focus. **Can you please confirm this is the case?**

**Could you please give an outline of all of the `HotKeys` components currently in focus? (Which ones define actions and/or handlers and how are they nested in relation to one another?)**

**Do you have any other handlers, or anything else that would trigger a change of focus when the ctrl key is pressed?**

**Could you please include more of the log that captures the components in question mounting, focusing and a ctrl keyevent being ignored?**

**Comment by OliverColeman** [comment]
Thanks for the prompt and detailed response!

Based on your comments I've experimented a bit more. Turns out that if I remove the element that I was using to control focus (taken from the docs/examples) - `<button style={autoFocusElStyle} ref={this.autoFocusElRefFn}  />` - it starts working just fine. I also tried using just `<button autoFocus style={autoFocusElStyle} />` but this also causes the issue. The reason I had this is so that I can use some shortcut keys for handlers defined on the "HotKeys Parent" element before clicking on anything with the mouse.

**Comment by OliverColeman** [comment]
I also found that programmatically setting the focus on the same element, instead of using autoFocus *and* in combination with autoFocus, causes the same issue, even with a delay of 200ms (after everything is rendered, I think).

**Comment by greena13** [comment]
After a couple of hours of prodding around, I am not sure I was ever able to reproduce your issue - I believe I made an error that lead me to conclude I was seeing your issue. It appears to be working as expected under the circumstances I previously said would cause the issue. 

I have also tried to replicate the setup from your description (using `autoFocus` and/or `ref.focus()`) and not been able to hit on a configuration that reproduces the issue.

I did find another minor issue that is somewhat related that could potentially solve your problem, or at least stop the `Ignored 'Control' keydown event because it had an old focus tree id` messages (which may be a Red Herring). Could you please try upgrading [v2.0.0-pre3](https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre3) and trying again?:

```
yarn upgrade react-hotkeys@next
```

If this does not change what you are seeing or fix your issue, could you please take a stab at creating a minimum reproducible example repo, so I can look into this further?

**Comment by greena13** [comment]
Hey OliverColeman, I've just released [v2.0.0-pre4](https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre4) and I *think* this may have resolved your issue. If you have time, could you please upgrade and check to see if you are still getting the same issue?

**Comment by OliverColeman** [comment]
It does seem to resolve the issue. Thanks!

**Comment by greena13** [comment]
Excellent! I'm very glad to hear it.
