### ISSUE TITLE
Unable to remove <document-fragment> when using HOC

### ISSUE THREAD

**Issue by Fleuv** [greena13/react-hotkeys#133]
React hotkeys drops in a `<document-fragment>` element inside my HTML document, how do I get rid of this element or how do I replace this element with a custom element or component.

**How are you using react hotkeys components?**
Via the withHotKeys HOC, I made a wrapper component what uses the HOC.

**Expected behavior**
No extra elements are inserted or the extra element is customizable or the events are passed onto another already existing element.

**Platform:**
 - Version of react-hotkeys: 1.1.4
 - Browser chrome, firefox
 - OS: linux/ubuntu

**Are you willing and able to create a PR request to fix this issue?** No, sorry.

**APPLICABLE TO v2.0.0-pre1 AND ABOVE:** Could be added as a new feature.

**Example application of this bug/feature:** https://codesandbox.io/s/84yovvwmr9

**Comment by greena13** [comment]
Hey Fleuv, thanks for taking the time to file an issue.

It looks like you are using v1.1.4, which unfortunately does not include any way to override the `document-fragment` component.

You have two choices:

1. Use [`<HotKeys>`](https://github.com/greena13/react-hotkeys/tree/v1.1.4#defining-hot-keys) instead of `withHotKeys`, which allows you to pass a `component` prop to customise the wrapper element.

1. Upgrade to the latest pre-release:

```
yarn upgrade react-hotkeys@next
```

`withHotKeys` [works differently](https://github.com/greena13/react-hotkeys#withhotkeys-hoc-api) in this release and solves your issue. Full upgrade instructions are available [here](https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre1).

I'm closing for now,  but please feel free to continue to comment here if you need any further clarification.
