### ISSUE TITLE
[BUG] @2.0.0-pre4 pressing Shift after Shift+Backspace continues triggering Shift+Backspace

### ISSUE THREAD

**Issue by vadzim** [greena13/react-hotkeys#143]
react-hotkeys version: 2.0.0-pre4

If there is a hotkey handler on Shift+Backspace, then pressing just Shift right after pressing Shift+Backspace triggers the same actions as pressing Shift+Backspace.

Code:
```javascript
import React, { Component } from "react";
import { HotKeys } from "react-hotkeys";
import logo from "./logo.svg";
import "./App.css";

const keyMap = {
  ShiftBackspace: "shift+backspace",
};

const handlers = {
  ShiftBackspace: () => alert("shift+backspace"),
};

const App = () => (
  <HotKeys keyMap={keyMap}>
    <HotKeys handlers={handlers}>
      <div className="App">
        <header className="App-header">
        </header>
      </div>
    </HotKeys>
  </HotKeys>
);

export default App;
```

Steps:

- press Shift+Backspace, an alert appears
- close alert (esc, enter, mouse)
- press Shift (alone, no Backspace)

Actual result:

- alert appears

Expected result:

- no alert appears

Example repo: https://github.com/vadzim/react-hotkeys-test/tree/f8c80b11074f496cad5dd9a2966ef7be8a79271e

**Comment by greena13** [comment]
Apologies for the delay, I have been away for a while.

I have to do some more testing, but I believe you are seeing this issue because you are choosing to display an alert dialog in your action handler, which is removing the focus from the document, so the `shift` and `escape` keyup events are never captured by `react-hotkeys`. i.e. `react-hotkeys` still thinks you are holding down `shift` and `escape` when you press `shift` for the second time.

You should not have this same issue if you have an event handler that does not cause the window to lose focus.

However, this is still a bug and I am working on an appropriate fix (currently toying with the idea of completely clearing the key history every time the window is blurred).

**Comment by StephenHaney** [comment]
I think we might be experiencing this too... our keymap looks like this:

```
  const keyMap: KeyMap = {
    UNDO: ['ctrl+z', 'command+z'],
    REDO: ['ctrl+y', 'command+shift+z'],
  };
```

REDO fires on command+shift (doesn't wait for the z)... unless you can't have 3 key combos mapped?

We're not doing anything to change focus.

**Comment by greena13** [comment]
Thank you for the extra information, @StephenHaney.

Would you mind opening a separate issue with further details and logs? I'd like to keep the scope of this issue to when the handler changes the window focus.
