### ISSUE TITLE
[FEATURE] Have key sequences support time

### ISSUE THREAD

**Issue by rostero1** [greena13/react-hotkeys#167]
**Is your feature request related to a problem? Please describe.**
I want to support ["comma", "m"] as my key sequence, but without a timeout value, the user could accidentally invoke the handler if they were to hit "comma" and then a minute later hit "m".

**Describe the solution you'd like**
I'd like to see key combos valid for only a certain period of time, maybe with something like a `keySequenceTimeout` prop.

**Describe alternatives you've considered**
Possibly showing key sequence presses as they happen.  So, show "," in a non-focusable window that the user can escape to cancel the key sequence. 

**Additional context**
None

**Comment by greena13** [comment]
Hi @rostero1, thanks for your suggestion.

It may be because it's late, but I'm afraid I am not sure what you are suggesting. Are you requesting that key sequences be honoured, even when another key is pressed in the meantime (up to a certain time-out period), or have I misunderstood?

Perhaps you could illustrate what you mean with a couple of user-stories or examples.

**Comment by greena13** [comment]
I'm afraid I'm going to have to close this issue due to inactivity. Let me know if you want to pick this up again.
