### ISSUE TITLE
[BUG] react-hotkeys increases bundle size with ~900kB

### ISSUE THREAD

**Issue by markuswustenberg** [greena13/react-hotkeys#174]
**Describe the bug**

Maybe it's a stretch calling this a bug, but react-hotkeys increased my app bundle size significantly, adding about 900kB unminified and uncompressed. I did not expect such a large size. Is there something that can be done to address this?

**How are you using react hotkeys components? (HotKeys, GlobalHotKeys, IgnoreKeys etc)**

GlobalHotKeys.

I'm importing it like so:

    import {GlobalHotKeys} from "react-hotkeys"

I'm using browserify with uglifyify and common-shakeify.

**Expected behavior**

That the bundle size would not increase so much.

**Platform (please complete the following information):**
 - Version: 2.0.0-pre5
 - Browser: Not relevant here.
 - OS: MacOS.

**Are you willing and able to create a PR request to fix this issue?**

Maybe, depends if there's a clear fix (like doing tree-shaking of the source or similar).

**Comment by markuswustenberg** [comment]
It looks like the library links to `cjs/react-hotkeys.production.min.js` when in the production environment, and that is only 60kB. Maybe I was too quick to file an issue and it's a problem with my build system. However, this problem doesn't appear with other libraries, so maybe there's something to be done to make it easier to integrate react-hotkeys without the size jump.

**Comment by markuswustenberg** [comment]
My full build command is:

    browserify -t babelify -t envify -t uglifyify -p common-shakeify sources/app.js | uglifyjs -m -c -o build/app-${VERSION}.js

**Comment by greena13** [comment]
Hey @markuswustenberg, thanks for expressing your concern. 

I have tried to be diligent with the package size to keep it as small as possible, including stripping out comments and minifying/uglifying the code in the production builds. You can find out (not much) more in the [Production optimizations](https://github.com/greena13/react-hotkeys#production-optimizations) section of the Readme.

I am also using rollup, which - as I understand it - provides the ability for ES6 tree shaking for ES6 applications. However, there is definitely the possibility that this has been configured incorrectly, or has since regressed in some way. It has been a long time since I set this up, that I no longer have any reliable recollection of the process or the behaviour. I would have to look back into it.

It's also been a long time since I worked with browserify and I dare say the tooling has moved on considerably from then. So I can be of little assistance on particulars of configuring your build system to pick up correct build.

I especially appreciate your feedback because I have not had much that relates to bundle size or how it is fitting into people's applications. 

You didn't mention whether it was your application's development or production build that was absorbing the development build of `react-hotkeys`. This would be a helpful starting point. Also, I would be very grateful to hear your experience with using other packages and how that differs from `react-hotkeys`.

Finally, I am curious if the intent is to absorb the `react-hotkeys` production bundle into your application's production bundle (recommended) or whether you are trying to absorb the development build of `react-hotkeys` and then use your build chain to minify it (not recommended).

**Comment by markuswustenberg** [comment]
Thank you for the detailed answer! Maybe the solution is to use a different bundler than browserify. I've been reluctant to switch because I set it up once at project start and it's been working okay since then, but perhaps now is the time to try something different. The web world tools move fast…

> You didn't mention whether it was your application's development or production build that was absorbing the development build of react-hotkeys. This would be a helpful starting point. Also, I would be very grateful to hear your experience with using other packages and how that differs from react-hotkeys.

The development build becomes 900kB bigger, the minified and compressed bundle gains only 150kB. But actually, I would expect packages to come in their source form, and that it's then up to the final application bundler to compress and minify as they see fit, and the library author shouldn't have to deal with that. The exception, of course, is when the library needs to go onto CDNs etc., but that is a different matter. Do you agree with this view?

> Finally, I am curious if the intent is to absorb the react-hotkeys production bundle into your application's production bundle (recommended) or whether you are trying to absorb the development build of react-hotkeys and then use your build chain to minify it (not recommended).

In this case I would expect the production build to become part of my production bundle. But again, I don't understand why there is a production bundle in the library in the first place, see above. I may be completely wrong though, as I've never written a javascript library for distribution.

Again, thank you for having taken the time to answer me! It's much appreciated.

**Comment by markuswustenberg** [comment]
A small update: I've switched to webpack, and now the production bundle size only increases with 40kB. In development the size difference is still significant, but I can definitely live with that. I think we can close this issue now, but I'll leave that up to you to decide.

**Comment by greena13** [comment]
> I would expect packages to come in their source form, and that it's then up to the final application bundler to compress and minify as they see fit, and the library author shouldn't have to deal with that

I'm afraid we disagree here. If I can summarise my understanding of the community conventions, it's the responsibility of the publishing libraries to do their own optimizations - because there is considerable variance between packages and the build tools they use, so it would be impossible for the consuming application to reliably build let alone meaningfully optimize all its dependencies. What is published by each library should instead be only what may need to be consumed. For `react-hotkeys`, this includes production-ready and development builds (that still include logging, comments and unminified code) for ES5 and ES6 (which should support tree shaking, if all is well). 

However, this is definitely an area in whicih I still have much to learn. The different module systems and the best ways to build, optimize and deliver them can be a great deal to manage. I appreciate all feedback and guidance on improvements to the process and the documentation around it, to make it easier for people to get the library with the smallest footprint possible.

I'm pleased you found a resolution to your problem. I'll be closing this thread for now, but I welcome further discussion or future issues with more actionable suggestions.
