### ISSUE TITLE
Observed one difference after upgrading to v2

### ISSUE THREAD

**Issue by ZYinMD** [greena13/react-hotkeys#213]
I observed one breaking change after upgrading to v2. I guess it's probably due adopting `SyntheticEvent`, and it's not a bug, but I want to report it and maybe get some comments on my code.

A simplified example of my app, working in v1.1.4:

```js
function MyList({ dataArray, addItem, focus }) {
  const keyMap = {
    NEW_ITEM: 'ctrl+n',
  };

  const handlers = {
    NEW_ITEM: () => {
      addItem('unique_id_0001'); // add a new element into dataArray, causing a re-render
      focus('unique_id_0001'); // focus on the new item
    },
  };

  return (
    <HotKeys handlers={handlers} keyMap={keyMap}>
      {dataArray.map(item => (...))}
    </HotKeys>
  );
}
```

Changes needed in v2 to keep the same functionality:
```diff
function MyList({ dataArray, addItem, focus }) {
  const keyMap = {
    NEW_ITEM: 'ctrl+n',
  };

  const handlers = {
    NEW_ITEM: () => {
      addItem('unique_id_0001'); // add a new element into dataArray, causing a re-render
-      focus('unique_id_0001');
+      setTimeout(() => {
+        focus('unique_id_0001');
+      }, 0);
    },
  };

  return (
    <HotKeys handlers={handlers} keyMap={keyMap}>
      {dataArray.map(item => (...))}
    </HotKeys>
  );
}
```

In v1.x, I was able to synchronously focus on the new element which didn't exist before the re-render, which I thought was magical, but it did work. In v2 I need to wait a tick, otherwise the new item can't be found. This produces a very noticeable delay (the re-render is fast, new item appears on the screen instantly, but the tick is surprisingly slow. Since the focus has a color change, it's very noticeable. It takes at least 200ms from new item appears on the screen to it getting focus).

I assume this is an expected change due to using `SyntheticEvent`? Is there something I can improve in my code? Thanks!

**Comment by greena13** [comment]
Hello again, @ZYinMD.

You are correct, that this is very likely due to the way the internals of v2 work. You are also right  to be suspicious of the original code - I am not sure how it ever (reliably) worked in the first place.

Mousetrap existed entirely outside of the React render cycle, making it difficult to reason about the exact order code would always be executed in. 

This is somewhat outside of what `react-hotkeys` actually handles, and is more in the realm of the JavaScript event system: The statements in your handlers are executed in sequence. If part of that handler code adds events to the JavaScript event queue (which occurs when you update state or props) then you need to wait for those messages to be processed before you can access the new DOM elements.

I suggest you try kicking the focus management to the browser by looking at the [autofocus](https://github.com/greena13/react-hotkeys#Autofocus) prop, if you are using a compatible HTML element. In short, this will auto-focus the last compatible element mounted to the DOM - which sounds exactly what you're trying to do. (NB: This is considered an anti-pattern by the a18n crowd, as it can confuse screen readers and the like. It's up to you to decide if this presents a problem for your application.)

Failing that, you may need to rig up something in [componentDidUpdate](https://reactjs.org/docs/react-component.html#componentdidupdate) to watch for changes in your props or state and re-focus accordingly.

It won't specifically solve your problem, but if you are doing a lot of focus and scroll management, you may find another of my libraries helpful: [react-ref-manager](https://github.com/greena13/react-ref-manager).

**Comment by ZYinMD** [comment]
Hi @greena13 thanks so much for your reply! I think re-focus in `componentDidUpdate` would work really well in my specific app, because it also solves another problem I had. I never thought about this approach before, thanks so much!!
