### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by jcready** [greena13/react-hotkeys#240]
@greena13 took over this repo in #72 less than a year ago. The 2.0.0 version was released and then there were no more responses to bug reports. The end of July seems like it marked the end of support for this project (no new commits, no responses to issues).

**Comment by knapeto** [comment]
Hey @jcready look at this screen:
![image](https://user-images.githubusercontent.com/8394226/66388286-0cdb3600-e9c6-11e9-894b-1dc467933d98.png)

It looks like @greena13 does not have much time to contribute for this package :( sad.. 

Would be great to change maintainer

**Comment by greena13** [comment]
Hi @jcready and @knapeto, this package is indeed still maintained. 

I have unfortunately had zero time to dedicate to it in the last couple of months due to a dramatic change in my paid employment. However, I do hope to continue to keep this project alive, with support from the community and perhaps some additional maintainers.

**Comment by greena13** [comment]
Closing this for now to help me triage outstanding issues, but please feel free to respond.
