### ISSUE TITLE
Add `ClassName` to interface props [Typescript]

### ISSUE THREAD

**Issue by PeterMK85** [greena13/react-hotkeys#84]
Currently this is ended up with an error
```
<HotKeys className={baseClass} keyMap={keyMap} ...
```

But it will be rendered totally fine
```
<div tabindex="-1" class="example_class"...
```

It's quite useful to have control over the `:focus` pseudo class based on a simple class.

**Comment by matthew-matvei** [comment]
I second this.

For me, the `<HotKeys />` wrapper was messing with heights of its children. I've gotten around it by adding `className` to internally-kept typings (which I don't want to do) and giving it a class that sets a height.

**Comment by greena13** [comment]
I've [updated the TypeScript](https://github.com/greena13/react-hotkeys/commit/fa8b0a71c9358e9550f8d9cc82380ce495022150) file in [v1.0.2](https://github.com/greena13/react-hotkeys/releases/tag/v1.0.2).

I am still relatively new to TypeScript and don't use it myself, so please let me know if this hasn't resolved your issue.

**Comment by matthew-matvei** [comment]
This has not solved the problem for me, and has introduced new ones. Shall we re-open this issue or begin a new one? The new problems for me are:

1. `className` not recognised as a valid prop (this is odd, since following the `extends` chain of your typings, this should ultimately come from `HTMLAttributes`). Maybe something got messed up in the chain
2. Both `keyMap` and `handlers` are required props, which doesn't match what I can see from your API. If there's been some update to that, I've probably missed it

You can verify this by cloning [FreeMAN](https://github.com/matthew-matvei/freeman) and checking out the `react-hotkeys-drop-typings` branch. `DirectoryWrapper.tsx` line 70 has an issue using `className="SomeClass"` and I `keyMap` is required, even though there's no keys to define within that component.

I'm happy to make a PR to fix these, either here or in the DefinitelyTyped project (they've got some pretty stringent procedures with types added).

**Comment by greena13** [comment]
@matthew-matvei, we'll re-open and continue discussing here.

My apologies - I seem to have been careless with the updates and *incorrectly*  left keyMap and handlers as required. 

I too was puzzled by why `className` didn't seem to be working for you. I thought the issue would maybe be resolved by importing `@types/react` rather than `react`. Apparently not.

I would appreciate any help you can give. Particularly if you could help me out with a pull request that fixes one or both of the above issues. As I don't use TypeScript, I've been relying on my IDE to parse and apply the TS definitions to test them - which is somewhat of an indirect approach. I'd prefer for you to update the definitions and test in the environment where you are having the problems.

My understanding is the best practice is to include the type definitions with the module, if at all possible, so let's try a PR into this repo.

Let me know if you need any help testing or diagnosing why `className` is not working.

**Comment by matthew-matvei** [comment]
@greena13 

No worries, it happens. Cool, I'll hopefully get some time later this week to have a look at it.

**Comment by cecton** [comment]
The import of `@types/react` breaks for me. I might give it some time to help you but if anyone wants to do it it will be faster I think.

> ERROR in [at-loader] ./node_modules/react-hotkeys/index.d.ts:1:24 
>    TS6137: Cannot import type declaration files. Consider importing 'react' instead of '@types/react'.

**Comment by greena13** [comment]
As there were a number of TypeScript issues preventing people from effectively using this package, I decided to do a [new release](https://github.com/greena13/react-hotkeys/releases/tag/v1.0.4) to fix them in a temporary fashion.

I will leave this issue open for 1 week, so that @matthew-matvei can look into why the `className` prop is not being inherited correctly as expect and @cecton to look into why importing `@types/react` is breaking things. 

I would still appreciate your brain power on both of those issues (happy to help however I can) but if no one says any differently within that one week, I'll assume the fixes I've put in place are sufficient to satisfy both your needs and curiosity.

**Comment by matthew-matvei** [comment]
This now lacks `onFocus` and `onBlur` props (since the solution for `className` only avoids the root issue. Judging by the latest `lib/HotKeys.js`, those props are still part of the API.

I'll fork and start getting a PR together to deal with it.
